name: Bug Report
description: Report a bug or issue
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        Hardware: Turing Pi 2 with 4x RK1 modules
        Talos Version:
        Kubernetes Version:
        RKNN SDK Version: (if applicable)
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
